name: rht_mobile_template
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  #State Management
  flutter_bloc: ^8.1.5
  provider: ^6.1.2

  #Network
  dio: ^5.4.3+1
  connectivity_plus: ^6.0.2

  #Dependecy Injection
  get_it: ^7.7.0

  #UI and Styling
  google_fonts: ^6.2.1
  loading_animation_widget: ^1.2.1
  animations: ^2.0.11
  badges: ^3.1.2

  #User Authentication
  local_auth: ^2.2.0

  #Utility
  equatable: ^2.0.5

  #Image Handling
  image_picker: ^1.1.0
  cached_network_image: ^3.3.1

  #Localization
  easy_localization: ^3.0.7
  intl: ^0.19.0

  #Notifications
  flutter_local_notifications: ^17.2.2

  #Firebase Integration
  firebase_messaging: ^15.0.4
  firebase_core: ^3.3.0

  #Other
  rxdart: ^0.27.7
  dartz: ^0.10.1
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.3
  lottie: ^3.1.2
  extended_masked_text: ^3.0.1
  lazy_load_indexed_stack: ^1.1.0
  share_plus: ^10.0.0
  path_provider: ^2.1.3
  animated_custom_dropdown: ^3.1.1
  change_app_package_name: ^1.3.0
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  retry: ^3.1.2
  infinite_scroll_pagination: ^4.0.0
  logging_service:
    git:
      url: https://github.com/samiraghayev12/logging.git


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1



flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter:

  uses-material-design: true

